=== andrej2431/DatoveFormaty/3/xml/schemas/schema-1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://example.org/xsd" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" targetNamespace="http://example.org/xsd" elementFormDefault="qualified" vc:minVersion="1.1"> 
    <xs:element name="database">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="zaměstnanci">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="tns:zaměstnanec" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
    
                <xs:element name="továrny">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="tns:továrna" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
    
                <xs:element name="automaty">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="tns:automat" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
    
                <xs:element name="sladkosti">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="tns:sladkost" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
    
                <xs:element name="suroviny">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="tns:surovina" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            
                <xs:element name="alergeny">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="tns:alergen" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="czech-text">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="lang" type="xs:string" fixed="cz"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:element name="zaměstnanec">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="tns:czech-text"/>
                <xs:element name="jméno" type="tns:czech-text"/>
                <xs:element name="příjmení" type="tns:czech-text"/>
                <xs:element name="tituly">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titul" type="tns:czech-text" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="továrna">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="tns:czech-text"/>
                <xs:element name="název" type="tns:czech-text"/>
                <xs:element name="rýchlost-výroby" type="xs:integer"/>

                <xs:element name="vyrábí">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sladkost-id" type="tns:czech-text" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="zaměstnává">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="zaměstnanec-id" type="tns:czech-text" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="automat">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="tns:czech-text"/>
                <xs:element name="název" type="tns:czech-text"/>
                <xs:element name="kapacita" type="xs:integer"/>
                <xs:element name="šířka" type="xs:integer"/>
                <xs:element name="délka" type="xs:integer"/>
                <xs:element name="výška" type="xs:integer"/>
    
                <xs:element name="nabízí">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sladkost-id" type="tns:czech-text" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="nachází-se-v">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tovarna-id" type="tns:czech-text" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="sladkost">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="tns:czech-text"/>
                <xs:element name="název" type="tns:czech-text"/>
                <xs:element name="hmotnost" type="xs:integer"/>
                <xs:element name="šířka" type="xs:integer"/>
                <xs:element name="délka" type="xs:integer"/>
                <xs:element name="výška" type="xs:integer" />
                <xs:element name="obsahujeSurovinu">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="surovina-id" type="tns:czech-text" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="surovina">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="tns:czech-text"/>
                <xs:element name="název" type="tns:czech-text"/>
                <xs:element name="cena-za-kg" type="xs:decimal"/>
                <xs:element name="obsahujeAlergen">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name ="alergen-id" type="tns:czech-text" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="alergen">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="tns:czech-text"/>
                <xs:element name="název" type="tns:czech-text"/>
                <xs:element name="číslo" type="xs:integer"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== andrej2431/DatoveFormaty/3/xml/data/data-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<database
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://example.org/xsd ../schemas/schema-1.xsd"
xmlns="http://example.org/xsd" >

    <zaměstnanci>
        <zaměstnanec>
            <id>Zeus</id>
            <jméno>Zeus</jméno>
            <příjmení>Hromný</příjmení>
            <tituly>
                <titul>Nej.</titul>
            </tituly>
        </zaměstnanec>

        <zaměstnanec>
            <id>Athena</id>
            <jméno>Athéna</jméno>
            <příjmení>Múdra</příjmení>
            <tituly>
                <titul>Pí</titul>
            </tituly>
        </zaměstnanec>

        <zaměstnanec>
            <id>Hades</id>
            <jméno>Hádes</jméno>
            <příjmení>Černý</příjmení>
            <tituly>
                <titul>PPodsv.</titul>
            </tituly>
        </zaměstnanec>

        <zaměstnanec>
            <id>Afrodita</id>
            <jméno>Afrodita</jméno>
            <příjmení>Krásna</příjmení>
            <tituly>
                <titul>Nejkr.</titul>
            </tituly>
        </zaměstnanec>

        <zaměstnanec>
            <id>Hermes</id>
            <jméno>Hermes</jméno>
            <příjmení>Kováč</příjmení>
            <tituly>
                <titul>Buch.</titul>
            </tituly>
        </zaměstnanec>

        <zaměstnanec>
            <id>Artemis</id>
            <jméno>Artemis</jméno>
            <příjmení>Lesná</příjmení>
            <tituly>
                <titul>Lesná.</titul>
            </tituly>
        </zaměstnanec>

        <zaměstnanec>
            <id>Apollo</id>
            <jméno>Apollo</jméno>
            <příjmení>Liečivý</příjmení>
            <tituly>
                <titul>Lig.</titul>
            </tituly>
        </zaměstnanec>
    </zaměstnanci>

    <továrny>
        <továrna>
            <id>TovárnaKarlíkova</id>
            <název>Karlíkova továrna na čokoládu</název>
            <rýchlost-výroby>32</rýchlost-výroby>
            <vyrábí>
                <sladkost-id>Tatranka</sladkost-id>
            </vyrábí>
            <zaměstnává>
                <zaměstnanec-id>Zeus</zaměstnanec-id>
                <zaměstnanec-id>Athena</zaměstnanec-id>
            </zaměstnává>
        </továrna>

        <továrna>
            <id>TovárnaHaribo</id>
            <název>Haribo Industries</název>
            <rýchlost-výroby>64</rýchlost-výroby>
            <vyrábí>
                <sladkost-id>Tatranka</sladkost-id>
                <sladkost-id>Nektar</sladkost-id>
            </vyrábí>
            <zaměstnává>
                <zaměstnanec-id>Hades</zaměstnanec-id>
                <zaměstnanec-id>Afrodita</zaměstnanec-id>
                <zaměstnanec-id>Hermes</zaměstnanec-id>
            </zaměstnává>
        </továrna>

        <továrna>
            <id>TovárnaCukPrum</id>
            <název>Cukrárenská průmyslovka</název>
            <rýchlost-výroby>128</rýchlost-výroby>
            <vyrábí>
                <sladkost-id>Nektar</sladkost-id>
                <sladkost-id>Tatranka</sladkost-id>
            </vyrábí>
            <zaměstnává>
                <zaměstnanec-id>Apollo</zaměstnanec-id>
                <zaměstnanec-id>Artemis</zaměstnanec-id>
            </zaměstnává>
        </továrna>
    </továrny>

    <automaty>
        <automat>
            <id>AutomatUVrátnice</id>
            <název>U Vrátnice</název>
            <kapacita>120</kapacita>
            <šířka>50</šířka>
            <délka>70</délka>
            <výška>200</výška>
            <nabízí>
                <sladkost-id>Tatranka</sladkost-id>
                <sladkost-id>Nektar</sladkost-id>
                <sladkost-id>ČokoDortík</sladkost-id>
            </nabízí>
            <nachází-se-v>
                <tovarna-id>TovárnaKarlíkova</tovarna-id>
            </nachází-se-v>
        </automat>

        <automat>
            <id>AutomatRychláMňamka</id>
            <název>Rychlá Mňamka</název>
            <kapacita>120</kapacita>
            <šířka>50</šířka>
            <délka>70</délka>
            <výška>70</výška>
            <nabízí>
                <sladkost-id>Tatranka</sladkost-id>
                <sladkost-id>Nektar</sladkost-id>
                <sladkost-id>čokoDortík</sladkost-id>
            </nabízí>
            <nachází-se-v>
                <tovarna-id>TovárnaHaribo</tovarna-id>
            </nachází-se-v>
        </automat>

        <automat>
            <id>AutomatPohoštěníVMezipatře</id>
            <název>Pohoštění V Mezipatře</název>
            <kapacita>110</kapacita>
            <šířka>50</šířka>
            <délka>40</délka>
            <výška>180</výška>
            <nabízí>
                <sladkost-id>Nektar</sladkost-id>
                <sladkost-id>ČokoDortík</sladkost-id>
            </nabízí>
            <nachází-se-v>
                <tovarna-id>TovárnaCukPrum</tovarna-id>
            </nachází-se-v>
        </automat>

        <automat>
            <id>AutomatOblačnéObčerstvení</id>
            <název>Oblačné Občerstvení</název>
            <kapacita>110</kapacita>
            <šířka>50</šířka>
            <délka>70</délka>
            <výška>180</výška>
            <nabízí>
                <sladkost-id>Nektar</sladkost-id>
                <sladkost-id>ČokoDortík</sladkost-id>
            </nabízí>
            <nachází-se-v>
                <tovarna-id>TovárnaCukPrum</tovarna-id>    
            </nachází-se-v>
        </automat>
    </automaty>

    <sladkosti>
        <sladkost>
            <id>Tatranka</id>
            <název>Tatranka</název>
            <hmotnost>125</hmotnost>
            <šířka>50</šířka>
            <délka>60</délka>
            <výška>120</výška>
            <obsahujeSurovinu>
                <surovina-id>Čokoláda</surovina-id>
                <surovina-id>Mléko</surovina-id>
                <surovina-id>Múka</surovina-id>
            </obsahujeSurovinu>
        </sladkost>

        <sladkost>
            <id>Nektar</id>
            <název>Nektar</název>
            <hmotnost>75</hmotnost>
            <šířka>60</šířka>
            <délka>60</délka>
            <výška>70</výška>
            <obsahujeSurovinu>
                <surovina-id>Múka</surovina-id>
                <surovina-id>Mléko</surovina-id>
                <surovina-id>Vejce</surovina-id>
                <surovina-id>Cukor</surovina-id>
                <surovina-id>Maslo</surovina-id>
            </obsahujeSurovinu>
        </sladkost>

        <sladkost>
            <id>ČokoDortík</id>
            <název>Čokoládový dortík</název>
            <hmotnost>50</hmotnost>
            <šířka>50</šířka>
            <délka>30</délka>
            <výška>80</výška>
            <obsahujeSurovinu>
                <surovina-id>Čokoláda</surovina-id>
                <surovina-id>Múka</surovina-id>
                <surovina-id>Maslo</surovina-id>
            </obsahujeSurovinu>
        </sladkost>
    </sladkosti>

    <suroviny>
        <surovina>
            <id>Múka</id>
            <název>múka</název>
            <cena-za-kg>24.90</cena-za-kg>
            <obsahujeAlergen>
                <alergen-id>Lepek</alergen-id>
            </obsahujeAlergen>
        </surovina>

        <surovina>
            <id>Maslo</id>
            <název>maslo</název>
            <cena-za-kg>56.49</cena-za-kg>
            <obsahujeAlergen>
                <alergen-id>MlékoAlergen</alergen-id>
            </obsahujeAlergen>
        </surovina>

        <surovina>
            <id>Cukor</id>
            <název>cukor</název>
            <cena-za-kg>20.12</cena-za-kg>
            <obsahujeAlergen></obsahujeAlergen>
        </surovina>

        <surovina>
            <id>Vejce</id>
            <název>vejce</název>
            <cena-za-kg>100.00</cena-za-kg>
            <obsahujeAlergen>
                 <alergen-id>VejceAlergen</alergen-id>
            </obsahujeAlergen>
        </surovina>

        <surovina>
            <id>Čokoláda</id>
            <název>čokoláda</název>
            <cena-za-kg>100.00</cena-za-kg>
            <obsahujeAlergen>
                <alergen-id>Arašidy</alergen-id>
                <alergen-id>MlékoAlergen</alergen-id>
            </obsahujeAlergen>
        </surovina>

        <surovina>
            <id>Mléko</id>
            <název>mléko</název>
            <cena-za-kg>23.42</cena-za-kg>
            <obsahujeAlergen>
                <alergen-id>MlékoAlergen</alergen-id>
            </obsahujeAlergen>
        </surovina>
    </suroviny>

    <alergeny>
        <alergen>
            <id>Lepek</id>
            <název>lepek</název>
            <číslo>1</číslo>
        </alergen>

        <alergen>
            <id>VejceAlergen</id>
            <název>vejce</název>
            <číslo>3</číslo>
        </alergen>

        <alergen>
            <id>Arašidy</id>
            <název>arašídy</název>
            <číslo>4</číslo>
        </alergen>

        <alergen>
            <id>Sója</id>
            <název>sója</název>
            <číslo>6</číslo>
        </alergen>

        <alergen>
            <id>MlékoAlergen</id>
            <název>mléko</název>
            <číslo>7</číslo>
        </alergen>
    </alergeny>
</database>
